### PR TITLE
Support for Child-Themes

### PR DESCRIPTION
**Pull request by Crease29**
I've added the support for showing a child-theme as mobile theme.

### CODE REVIEW

**Comment by MantasVaitkunas** [comment]
Hi @Crease29, thanks for contribution. We are waiting PO decision regarding your pull request.

**Comment by flo1o1** [comment]
Hi @Crease29, thanks again for your contribution. I added it to the product backlog. We will have a look at it and integrate your PR in one of our upcoming sprints.

**Comment by kermie** [comment]
Waiting for CLA signing before merging it.

**Comment by Crease29** [comment]
Done

**Pull request closed without merging**
